In [53]:
from scipy.stats.stats import pearsonr
from sklearn.model_selection import train_test_split
import pickle
import os
import csv 
import pandas as pd
import statistics as stat
import numpy as np
import math

#STEP 1 : COUNT ALL SIMILARITIES IN 1 ROW
#STEP 2 : IF COUNTED SIMILARITIES MORE THAN 37, DELETE COLUMN

# dtTrain = pd.read_csv("data/TrainSetNoId.csv")
dtTrain = pickle.load( open( "pickle/train.pkl", "rb" ) )
dtTrain.head()

,nAcid,ALogP,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,nH,...,P2s,E1s,E2s,E3s,Ts,As,Vs,Ks,Ds,pIC50
25,0,-0.3792,0.143793,95.7257,46.054309,17,19,37,24,13,...,0.213900,0.589992,0.550366,0.180541,19.195738,66.593446,104.821981,0.654636,1.320899,5.638
9,0,-2.1104,4.453788,129.7840,69.909411,17,19,60,33,27,...,0.315636,0.627324,0.427534,0.372554,28.776159,198.480482,405.367508,0.471712,1.427413,7.086
20,0,-0.8571,0.734620,115.9860,60.628653,17,19,51,30,21,...,0.162506,0.562672,0.442445,0.346526,30.841801,149.876581,283.053745,0.716541,1.351643,7.921
18,0,-0.4120,0.169744,121.2063,61.430653,17,19,52,31,21,...,0.217150,0.581178,0.446674,0.292804,29.122886,160.182183,290.497609,0.636938,1.320656,7.921
67,0,0.4644,0.215667,129.1337,65.827032,16,18,55,31,24,...,0.136583,0.560517,0.334018,0.472880,32.007329,155.151568,337.271370,0.734012,1.367415,7.046

In [54]:
def similarValue(dframe):
    colList = [] #List for column
    # colDframe = dframe.columns.values #get all columns
    for j in range(0,dframe.shape[1]):
        topEl = stat.mode(dframe.iloc[:,j]) # Get modus value from j column
        duplicate = 0
        # Loop comparing each row with modus
        for i in range(0,74):
            comp = dframe.iloc[i,j]
            if comp == topEl:
                duplicate += 1
        if duplicate >= 37 :
            colList.append(j)    
    return colList

def stdDeviation(dframe):
    stdevList = []
    # colDframe = dframe.columns.values
    for j in range(0,dframe.shape[1]-1):
        # Loop search standard deviation each column
        stddev = 0
        sample = dframe.iloc[:,j] #Get all row in j column for standard deviation
        stddev = np.std(sample) #Get standard deviation from 'sample' list
        if stddev <= 0.95 :
            # print(j, "PICKED")
            stdevList.append(j)
    return stdevList

def checkNa(dframe):
    naList = []
    # colDframe = dframe.columns.values
    for j in range(0,dframe.shape[1]):
        cknan = dframe.iloc[0,j]
        if math.isnan(cknan): #Check NaN value at row 0 in column j
            naList.append(j)
    return naList

def checkInf(dframe):
    infList = []
    colDframe = dframe.columns.values
    for j in range(0,len(colDframe)):
        cknan = dframe.iloc[0,j]
        if math.isinf(cknan): #Check Infinite value at row 0 in column j
            infList.append(j)
    return infList

def checkDupLabel(dframe):
    dupLabel = []
    for i in range(0,dframe.shape[1]):
        label = dframe.columns.values[i]
        for j in range(i+1, dframe.shape[1]):
            if(label == dframe.columns.values[j]):
                print(0)
    return dupLabel

def lowCorrP(dframe):
    label_ = dframe.columns.values
    pic50 = dframe.iloc[:,-1]
    corr_y = [pearsonr(dframe.iloc[:,i],pic50) for i in range(dframe.shape[1])]
    corr_y = [np.abs(corr_y[i][0]) for i in range(dframe.shape[1])]
    corr_lim = 0.20
    hi_corr = []
    for i in range(len(corr_y)):
        if corr_y[i] > corr_lim:
            hi_corr.append(i)
    label_idx = label_[hi_corr]
    dtLowCorr = dframe.loc[:,label_idx]
    # print(X_train)
    print("descriptor number after removing low correlation with target: {}".format(dtLowCorr.shape[1]))
    return dtLowCorr

def lowCorrPMod(dframe):
    label_ = dframe.columns.values
    pic50 = dframe.iloc[:,-1]
    corr_y = [pearsonr(dframe.iloc[:,i],pic50) for i in range(dframe.shape[1])]
    corr_y = [np.abs(corr_y[i][0]) for i in range(dframe.shape[1])]
    corr_lim = 0.20
    hi_corr = []
    for i in range(len(corr_y)):
        if corr_y[i] > corr_lim:
            hi_corr.append(i)
    label_idx = label_[hi_corr]
    dtLowCorr = dframe.loc[:,label_idx]
    # print(X_train)
    print("descriptor number after removing low correlation with target: {}".format(dtLowCorr.shape[1]))
    return corr_y

def highCorrP(dframe):
    # -----------REMOVE FEATURE WITH HIGH CORRELATION TO OTHER FEATURE---------------------
    # re-calculate correlation with pic50
    label_ = dframe.columns.values
    pic50 = dframe.iloc[:,-1]
    corr_y = [pearsonr(dframe.iloc[:,i],pic50) for i in range(dframe.shape[1])]
    corr_y = [np.abs(corr_y[i][0]) for i in range(dframe.shape[1])]
    desc_num = dframe.shape[1]
    # calculate correlation for each descriptor
    corr_matrix = np.corrcoef(dframe.T)
    corr_lim = 0.80
    low_corr = np.arange(desc_num).tolist()
    tmp = np.arange(desc_num).tolist()
    for i in np.arange(desc_num):
        tmp.remove(i)
        for j in tmp:
            corr_ = np.abs(corr_matrix[i,j])
            if corr_ >= corr_lim:
                if corr_y[i] > corr_y[j]:
                    if j in low_corr:
                        low_corr.remove(j)
                else:
                    if i in low_corr:
                        low_corr.remove(i)
    label_idx = label_[low_corr]
    dtHiCorr = dframe.loc[:,label_idx]
    print("descriptor number after removing high correlation descriptor: {}".format(dtHiCorr.shape[1]))
    return dtHiCorr

def highCorrPMod(dframe):
    # -----------REMOVE FEATURE WITH HIGH CORRELATION TO OTHER FEATURE---------------------
    # re-calculate correlation with pic50
    label_ = dframe.columns.values
    pic50 = dframe.iloc[:,-1]
    corr_y = [pearsonr(dframe.iloc[:,i],pic50) for i in range(dframe.shape[1])]
    corr_y = [np.abs(corr_y[i][0]) for i in range(dframe.shape[1])]
    desc_num = dframe.shape[1]
    # calculate correlation for each descriptor
    corr_matrix = np.corrcoef(dframe.T)
    corr_lim = 0.80
    low_corr = np.arange(desc_num).tolist()
    tmp = np.arange(desc_num).tolist()
    for i in np.arange(desc_num):
        tmp.remove(i)
        for j in tmp:
            corr_ = np.abs(corr_matrix[i,j])
            if corr_ >= corr_lim:
                if corr_y[i] > corr_y[j]:
                    if j in low_corr:
                        low_corr.remove(j)
                else:
                    if i in low_corr:
                        low_corr.remove(i)
    label_idx = label_[low_corr]
    dtHiCorr = dframe.loc[:,label_idx]
    print("descriptor number after removing high correlation descriptor: {}".format(dtHiCorr.shape[1]))
    return corr_y

def dropColumn(dframe, tList):
    dropped = pd.DataFrame() #Create empty dataframe
    dropped = dframe.drop(dframe.columns[tList], axis=1) #drop column based on list by column
    return dropped

In [55]:
dtTrain.shape

(74, 1876)

In [56]:
##### STEP 0 Reduces NAN Values
raw = len(dtTrain.columns)
dtTrain.dropna(axis=1, how='any', thresh=None, subset=None, inplace=True)
print("#0. Trainset ", dtTrain.shape[1] , " | ", raw-dtTrain.shape[1], " NaN value columns removed")

#0. Trainset  1876  |  0  NaN value columns removed

In [57]:
##### STEP 1 Reduces similarity
# simValList = similarValue(dtTrain)
# print("#1. Trainset ", dtTrain.shape[1] , " | ", dtTrain.shape[1] - len(simValList) , " similarity value columns removed")
# dtTrain = dropColumn(dtTrain,simValList)

In [58]:
##### STEP 2 Reduce columns by Standard Deviation
# sdList = stdDeviation(dtTrain)
# print("#2. Trainset ", dtTrain.shape[1] , " | ", dtTrain.shape[1] - len(sdList) , " standard deviation below 0.95 value columns removed")
# dtTrain = dropColumn(dtTrain,sdList)

In [59]:
###### STEP 3  Low Correlations
dtTrain = lowCorrPMod(dtTrain)

descriptor number after removing low correlation with target: 1059

In [60]:
sortedtr = dtTrain.sort()

In [9]:
###### STEP 4 High Correlations
dtTrain = highCorrP(dtTrain)

descriptor number after removing high correlation descriptor: 78

In [10]:
dtTrain.to_pickle("./pickle/train_reduced.pkl")
dtTrain.head()

,AATS8p,AATS1i,AATS6i,AATS7i,ATSC6c,ATSC7c,ATSC1i,ATSC2i,ATSC5i,AATSC8i,...,RDF95m,RDF45s,RDF70s,RDF75s,RDF115s,Dm,E1i,Di,E2s,pIC50
25,1.294533,146.167203,157.658067,158.709352,0.138045,-0.232985,12.505466,-9.826647,-2.057857,-0.035732,...,2.603393,29.384407,8.610602,14.280618,3.240336,0.830718,0.612566,1.423903,0.550366,5.638
9,1.387268,148.270745,162.707989,157.620767,0.011044,-0.239539,3.748805,7.653110,25.982876,0.078857,...,10.987896,41.940020,17.948384,23.997174,16.717840,0.977679,0.661392,1.491735,0.427534,7.086
20,1.444304,148.968590,162.762712,156.215156,0.081019,-0.159473,7.228374,5.544557,-13.260566,-0.064778,...,6.382991,43.683218,23.392357,22.449568,9.581508,0.789643,0.597492,1.446236,0.442445,7.921
18,1.442204,149.520799,163.318981,156.505126,0.240519,-0.192962,3.465851,10.220538,-7.460539,-0.082709,...,7.248164,42.014603,16.918042,20.544289,11.313925,0.922115,0.609907,1.376195,0.446674,7.921
67,1.485366,149.434802,164.872301,158.506227,0.113007,-0.000914,1.973198,34.543415,-1.458835,-0.087701,...,5.305829,46.117476,16.704478,21.496263,6.860493,0.828928,0.593172,1.452144,0.334018,7.046